# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE UI will override any settings specified in this file.

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enables AndroidX for dependency resolution
android.useAndroidX=true

# Enables non-transitive R classes to reduce app size and build speed
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official
